### ISSUE TITLE
Eseguire uno script Python

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld#1]
Ho caricato il file `helloworld.py`.
Sincronizza la tua cartella locale con pull
oppure effettua un clone se ancora non lo hai fatto.

Poi manda in esecuzione con
```bash
$ python helloworld.py
```

**Comment by FabioZTessitore** [comment]
Ho aggiunto `variabili.py`
Dimmi se tutto chiaro

**Comment by LuigiVessella** [comment]
Chiarissimo

2016-11-03 14:54 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ok, caricato input.py

ti assegno degli esercizi sotto forma di issue

**Comment by LuigiVessella** [comment]
Ok..Ora per richiamare l'IDE di sviluppo faccio come ruzzon?
Cioè file di testo e poi lo compilo?

2016-11-03 14:58 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
non ho idea di quale IDE stiate usando ... mah
come hai fatto con helloworld che ti ho mandato?

ps. python è un linguaggio interpretato, non compilato

**Comment by LuigiVessella** [comment]
Ide ho sbagliato io a dirlo, intendevo il terminale, comunque ora sto caricando gli esercizi, tutto chiaro.
