### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld#2]
Creare un programma hello.py che chieda il nome
dell'utente e poi stampi la stringa "Hello, <yourname>"

**Comment by FabioZTessitore** [comment]
1) avevo chiesto un file di nome `hello.py`
2) il prompt e la richiesta di input possono (e devono) andare insieme

**Comment by LuigiVessella** [comment]
Ok ora risolvo subito capo! Ahah

**Comment by LuigiVessella** [comment]
Fatto! Caricato hello.py

**Comment by FabioZTessitore** [comment]
ok, poi il vecchio lo cancelli
