### ISSUE TITLE
Doppio

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld#3]
Creare un programma doppio.py che chiede all'utente
di inserire un numero intero e quindi stampa
il doppio del numero inserito.

**Comment by FabioZTessitore** [comment]
cerca di mantenere i nomi che ti assegno

**Comment by LuigiVessella** [comment]
Ah scusate questo è un brutto vizio, di solito li nomino come mi fa comodo

**Comment by FabioZTessitore** [comment]
non va bene perché devi abituarti a lavorare in team. se ti chiedo un file con un certo nome può darsi che nella mia parte di programma io faccia riferimento a quel nome. se lo cambi non funziona più

ps. a parte il fatto che mi costringi a cercare ...
