### ISSUE TITLE
Sfera

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld#5]
Creare un programma sfera.py che chieda all'utente
il raggio di una sfera (intero) e ne stampi superficie e volume

Note:
Per portare a termine il compito e'
necessaria la costante matematica pi greco.
Si puo' definire una variabile assegnandole tale valore:
```python
pi = 3.141592654
```
Oppure si puo' utilizzare quella gia'
definita nella libreria matematica:
```python
import math

...

math.pi

...
```

**Comment by LuigiVessella** [comment]
Fatto!

**Comment by FabioZTessitore** [comment]
devi fare le seguenti modifiche
1) utilizzare numeri float e non int nelle equazioni
2) usare il valore di pi greco  della libreria matematica

**Comment by LuigiVessella** [comment]
Fatto!

**Comment by FabioZTessitore** [comment]
non ci siamo capiti
il raggio dato in input deve essere intero come avevi fatto prima. sono le costanti numeriche che devono essere float e non int

**Comment by LuigiVessella** [comment]
Prof per favore modificatelo voi il file perchè non ho capito di nuovo...
A me il programma funzione con tutti i valori sia interi che decimali, a cosa devo mettere float e perchè?

**Comment by FabioZTessitore** [comment]
lo so che funziona, non ho detto il contrario.
Quando nelle formule si usano dei numeri devono essere float

**Comment by LuigiVessella** [comment]
Ho aggiornato il file sfera e messo equazione.py
