### ISSUE TITLE
eq primo grado

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld#6]
```
elif termX != 0 and termN == 0:
   ris =float (termN) / float (termX)
   print "La soluzione dell'equazione e' x = ",ris
```
se termN è 0 e termX no verrà sempre 0, a che serve il calcolo?

### riordino del codice
prova a scrivere il codice in questo modo:
se termX e termN sono 0:
...
se termX è zero:
...
altrimenti:
...

risulterà molto più chiaro e ti sarà da modello per risolvere quelle di secondo grado

**Comment by LuigiVessella** [comment]
Immaginavo che me l'avreste detto ahah...
Provvedo subito

**Comment by LuigiVessella** [comment]
Fatto!

**Comment by FabioZTessitore** [comment]
```
elif termX == 0 and termN !=0:
```

qui non è necessario aggiungere termN!=0 perché nel caso precedente hai chiesto se era 0, quindi qui deve essere per forza diverso da 0

**Comment by LuigiVessella** [comment]
Eh si sono dettagli questi ahaha;)
Ora correggo, poi carico quelle di 2 grado e apro una nuova repository sull'html
