### ISSUE TITLE
SecGrado

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld#7]
Scrivi un programma che trovi le soluzioni a equazioni di secondo grado
nella forma ax^2+bx+c=0, con a, b e c interi.
Il programma dovrebbe tener conto dei casi particolari.

Per il calcolo della radice quadrata si puo' utilizzare la funzione `sqrt()`
della libreria matematica math
```python
import math

... math.sqrt() ...
```

**Comment by LuigiVessella** [comment]
Devo provare tutte le possibilità?
Cioè completa, incompleta spuria e pura?

**Comment by FabioZTessitore** [comment]
ragiona come ti ho fatto vedere per quelle di primo grado

**Comment by LuigiVessella** [comment]
Ok perfetto sto facendo..tra qualche minuto carico

**Comment by LuigiVessella** [comment]
Sto perfezionando ahah

**Comment by LuigiVessella** [comment]
Ok..prof provate ma non sono sicuro che sia corretto, anzi sono sicuro che non va bene ahah..
Se metto 6x2 e 4x nel secondo caso mi da -1.0

**Comment by FabioZTessitore** [comment]
se ti metti a ragionare in termini di != 0 non te ne esci
Ti ho già detto di fare come in equazioni di I grado

**Comment by LuigiVessella** [comment]
In questo modo quindi?
Se mi dite che come struttura va bene passo alle formule fatte bene...

**Comment by FabioZTessitore** [comment]
NI
qui i coefficienti sono 3, non 2

**Comment by LuigiVessella** [comment]
Vedete ora, le sto provando tutte e non va quella senza il termine in x.....
Altrimenti chiedo aiuto a Ruzzon ahah

**Comment by FabioZTessitore** [comment]
testardo
devi usare lo stesso modello usato per le eq di primo grado:
prima controlli se i termini sono tutti nulli, poi controlli solo i primi due e così via

**Comment by LuigiVessella** [comment]
Si prof ho fatto anche così prima...Ma il risultato è sempre lo stesso..

**Comment by FabioZTessitore** [comment]
fai e fidati

**Comment by LuigiVessella** [comment]
Prima ho fatto come potete vedere ora..

**Comment by LuigiVessella** [comment]
Ovvio che mi fido prof!

**Comment by FabioZTessitore** [comment]
partiamo da questa versione. Manca il termine in x^2

**Comment by LuigiVessella** [comment]
Si devo fare:
1) x2==0 and x==0 and N==0:
2) x2== 0:
Quale mi conviene? Nel secondo caso si trasforma in equazione di 1 grado..
Li metto entrambi?

**Comment by FabioZTessitore** [comment]
ci vogliono tutti
1) x2==0 and x==0 and N==0:
2) x2== 0 and x==0:
3) x2==0:
4) else

**Comment by LuigiVessella** [comment]
Fatto!

**Comment by LuigiVessella** [comment]
Ora dovrebbero esserci tutti i casi possibili

**Comment by FabioZTessitore** [comment]
No. Ce ne sono troppi. I casi sono 4

**Comment by LuigiVessella** [comment]
Mi sembra strano..Con 4 non si risolvono tutti i tipi di equazione di 2 grado..
Completa
Incompleta spuria
Incompleta pura
Equazione monomia
E in questo caso anche quando diventa di primo, cioè dove si annulla x2

**Comment by FabioZTessitore** [comment]
alcune di queste si risolvono allo stesso modo

**Comment by LuigiVessella** [comment]
Prof dato che oggi è Domenica non voglio disturbarvi..Ora ci ragiono un altro po' da solo e domani in classe la controlliamo;)
Buona serata!

**Comment by FabioZTessitore** [comment]
come preferisci, se trovi una soluzione inviala

**Comment by LuigiVessella** [comment]
Va benissimo!

**Comment by LuigiVessella** [comment]
Fatto!

**Comment by FabioZTessitore** [comment]
ma fatto che? devono essere 4 casi
1) x^2 == 0 and x == 0 and N == 0:
2) x^2 == 0 and x == 0:
3) x^2 == 0:
4) else

**Comment by LuigiVessella** [comment]
Spero di aver fatto bene stavolta...

**Comment by FabioZTessitore** [comment]
ok, ringrazia carlo e se hai dei dubbi poi ne parliamo a voce.
